--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_SCREENS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."APP_SCREENS" 
   (	"SCREEN_CODE" VARCHAR2(100 BYTE), 
	"SCREEN_NAME" VARCHAR2(200 BYTE), 
	"SCREEN_DESC" VARCHAR2(300 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"CREADTED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index APP_SCREENS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."APP_SCREENS_PK" ON "ETCHCM"."APP_SCREENS" ("SCREEN_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APP_SCREENS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."APP_SCREENS" MODIFY ("SCREEN_CODE" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_SCREENS" ADD CONSTRAINT "APP_SCREENS_PK" PRIMARY KEY ("SCREEN_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
