--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_ROLE_DEPARTMENTS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."APP_ROLE_DEPARTMENTS" 
   (	"ROLE_ID" NUMBER, 
	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ENABLED_FLAG" VARCHAR2(3 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_APP_ROLE_DEPT_U1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."PK_APP_ROLE_DEPT_U1" ON "ETCHCM"."APP_ROLE_DEPARTMENTS" ("ROLE_ID", "DEPT_CATEGORY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APP_ROLE_DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."APP_ROLE_DEPARTMENTS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_ROLE_DEPARTMENTS" MODIFY ("DEPT_CATEGORY_CODE" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_ROLE_DEPARTMENTS" ADD CONSTRAINT "PK_APP_ROLE_DEPT_U1" PRIMARY KEY ("ROLE_ID", "DEPT_CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_ROLE_DEPARTMENTS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."APP_ROLE_DEPARTMENTS" ADD CONSTRAINT "FK_APP_ROLE_DEPT_N1" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ETCHCM"."APP_ROLES" ("ROLE_ID") ENABLE;
