--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APP_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."APP_USER_ROLES" 
   (	"ACCESS_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"ROLE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"ENABLED_FLAG" VARCHAR2(3 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"CURRENT_ACTIVE_FLAG" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0016096
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0016096" ON "ETCHCM"."APP_USER_ROLES" ("ACCESS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table APP_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."APP_USER_ROLES" MODIFY ("ACCESS_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_USER_ROLES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."APP_USER_ROLES" ADD PRIMARY KEY ("ACCESS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APP_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."APP_USER_ROLES" ADD CONSTRAINT "FK_APP_ROLE_N2" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "ETCHCM"."APP_ROLES" ("ROLE_ID") ENABLE;
