--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CC_SUMMARY_N
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."CC_SUMMARY_N" 
   (	"HCM_EMPLOYEE_NUM" NUMBER(8,0), 
	"EVENT_DAY" VARCHAR2(26 BYTE), 
	"REQUEST_NUMBER" NUMBER(8,0), 
	"TIME_TYPE_VALUE" VARCHAR2(26 BYTE), 
	"PUNCH_TIME_IN" VARCHAR2(26 BYTE), 
	"PUNCH_TIME_OUT" VARCHAR2(26 BYTE), 
	"HOURS" NUMBER(22,18), 
	"SOURCE_ID" VARCHAR2(26 BYTE), 
	"DEVICE_ID" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
