--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HCM_EMPS_BK
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."HCM_EMPS_BK" 
   (	"PERSON_ID" NUMBER(*,0), 
	"PERSON_NUMBER" VARCHAR2(100 BYTE), 
	"PERSON_NAME" VARCHAR2(200 BYTE), 
	"AGENCY_NUMBER" VARCHAR2(100 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(100 BYTE), 
	"BPA1" VARCHAR2(100 BYTE), 
	"BPA2" VARCHAR2(100 BYTE), 
	"BPA3" VARCHAR2(100 BYTE), 
	"BPA4" VARCHAR2(100 BYTE), 
	"BPA5" VARCHAR2(100 BYTE), 
	"ORGANIZATION_ID" NUMBER(*,0), 
	"DEPARTMENT_NAME" VARCHAR2(500 BYTE), 
	"JOB_ID" NUMBER(*,0), 
	"JOB_NAME" VARCHAR2(500 BYTE), 
	"JOB_CODE" VARCHAR2(200 BYTE), 
	"POSITION_ID" NUMBER(*,0), 
	"POSITION_NAME" VARCHAR2(500 BYTE), 
	"POSITION_CODE" VARCHAR2(200 BYTE), 
	"CONTRACT_TYPE" VARCHAR2(200 BYTE), 
	"CONTRACT_NAME" VARCHAR2(500 BYTE), 
	"PERSON_TYPE_ID" NUMBER(*,0), 
	"SYSTEM_PERSON_TYPE" VARCHAR2(100 BYTE), 
	"USER_PERSON_TYPE" VARCHAR2(200 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(200 BYTE), 
	"ATTENDANCE_SOURCE" VARCHAR2(50 BYTE), 
	"OLD_EMLPOYEE_NUMBER" VARCHAR2(50 BYTE), 
	"EMPLOYMENT_CATEGORY" VARCHAR2(100 BYTE), 
	"ACTIVE_FLAG" VARCHAR2(10 BYTE), 
	"SALARY_AMOUNT" NUMBER, 
	"EMPLOYMENT_STATUS" VARCHAR2(50 BYTE), 
	"MANAGER_ID" NUMBER, 
	"OLD_JOB_ID" NUMBER, 
	"RC_JOB_CODE" VARCHAR2(200 BYTE), 
	"ASSIGNMENT_ID" NUMBER, 
	"ASSIGNMENT_NUMBER" VARCHAR2(100 BYTE), 
	"SHIFT_DAYS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
