--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OIC_INT_TRACKER_ERRORS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."OIC_INT_TRACKER_ERRORS" 
   (	"TRACKER_HDR_ID" NUMBER, 
	"TRACKER_LINE_ID" NUMBER, 
	"SOUECE_NAME" VARCHAR2(1000 BYTE), 
	"SOUECE_VALUE" VARCHAR2(300 BYTE), 
	"SOUECE_ID" NUMBER, 
	"EXCEPTION_REMARK" VARCHAR2(1000 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PAYLOAD" CLOB, 
	"E_MESSAGE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("E_MESSAGE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  Ref Constraints for Table OIC_INT_TRACKER_ERRORS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."OIC_INT_TRACKER_ERRORS" ADD CONSTRAINT "FK_OICINT_TRK_HD_ID" FOREIGN KEY ("TRACKER_HDR_ID")
	  REFERENCES "ETCHCM"."OIC_INT_TRACKER_HEADERS" ("TRACKER_HDR_ID") ENABLE;
