--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_PAYMENT_TRX_LINES
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_PAYMENT_TRX_LINES" 
   (	"TRX_LINE_ID" NUMBER, 
	"TRX_HEADER_ID" NUMBER, 
	"TRX_LINE_NUMBER" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"ATTENDANCE" NUMBER, 
	"ABSENCE" NUMBER, 
	"SALARY" NUMBER, 
	"COMMISSION" NUMBER, 
	"OVERTIME" NUMBER, 
	"INCENTIVE" NUMBER, 
	"EXPENSES" NUMBER, 
	"AIRFARE" NUMBER, 
	"INSURANCE" NUMBER, 
	"OTHER_BENEFITS" NUMBER, 
	"OTHER_DEDUCTIONS" NUMBER, 
	"BILL_AMOUNT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"ABSENCE_AMOUNT" NUMBER, 
	"ADHOCPAY_AMOUNT" NUMBER, 
	"WORKMAN_COMP_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015810
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015810" ON "ETCHCM"."PTE_PAYMENT_TRX_LINES" ("TRX_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_PAYMENT_TRX_LINES
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_LINES" MODIFY ("TRX_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_LINES" ADD PRIMARY KEY ("TRX_LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PTE_PAYMENT_TRX_LINES
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_LINES" ADD CONSTRAINT "FK_PTE_TRX_LINE_ID" FOREIGN KEY ("TRX_HEADER_ID")
	  REFERENCES "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" ("TRX_HEADER_ID") ENABLE;
