--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_PAYMENT_TRX_BPAS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_PAYMENT_TRX_BPAS" 
   (	"TRX_BPA_ID" NUMBER, 
	"TRX_HEADER_ID" NUMBER, 
	"BPA_TYPE" VARCHAR2(30 BYTE), 
	"BPA_NUMBER" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"BR_NUMBER" NUMBER, 
	"BR_AMOUNT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"SET_HDR_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015792
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015792" ON "ETCHCM"."PTE_PAYMENT_TRX_BPAS" ("TRX_BPA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_PAYMENT_TRX_BPAS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_BPAS" MODIFY ("TRX_BPA_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_BPAS" ADD PRIMARY KEY ("TRX_BPA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PTE_PAYMENT_TRX_BPAS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_BPAS" ADD CONSTRAINT "FK_PTE_TRX_BPA_ID" FOREIGN KEY ("TRX_HEADER_ID")
	  REFERENCES "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" ("TRX_HEADER_ID") ENABLE;
