--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_SUPPLIER_POS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_SUPPLIER_POS" 
   (	"PO_HEADER_ID" NUMBER, 
	"PO_NUMBER" VARCHAR2(30 BYTE), 
	"SUPPLIER_NUMBER" VARCHAR2(30 BYTE), 
	"PO_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"PO_DATE" DATE, 
	"EBS_ORG_ID" NUMBER, 
	"PO_TYPE_CODE" VARCHAR2(50 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"PO_AMOUNT" NUMBER, 
	"CURRENCY_CODE" VARCHAR2(30 BYTE), 
	"ENABLED_FLAG" VARCHAR2(3 BYTE), 
	"VENDOR_ID" NUMBER, 
	"VENDOR_SITE_ID" NUMBER, 
	"BILL_TO_LOCATION_ID" NUMBER, 
	"SHIP_TO_LOCATION_ID" NUMBER, 
	"TERMS_ID" NUMBER, 
	"FREIGHT_TERMS" VARCHAR2(30 BYTE), 
	"GMA_REF" VARCHAR2(150 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(150 BYTE), 
	"APPROVED_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"BALANCE_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
