--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_LOG_DETAIL
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_LOG_DETAIL" 
   (	"LOG_ID" NUMBER, 
	"PROCESS_NAME" VARCHAR2(300 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE), 
	"LOG_DATE" DATE, 
	"REQUEST_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(20 BYTE), 
	"EMPLOYEE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015744
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015744" ON "ETCHCM"."PTE_LOG_DETAIL" ("LOG_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_LOG_DETAIL
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_LOG_DETAIL" MODIFY ("LOG_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_LOG_DETAIL" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
