--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_PAYMENT_TRX_HEADERS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" 
   (	"TRX_HEADER_ID" NUMBER, 
	"TRX_NUMBER" VARCHAR2(30 BYTE), 
	"TRX_DATE" DATE, 
	"TRX_AMOUNT" NUMBER, 
	"AGENCY_NUMBER" NUMBER, 
	"AGENCY_ID" NUMBER, 
	"PERIOD_NAME" VARCHAR2(30 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"ELEMENT_SET_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015790
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015790" ON "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" ("TRX_HEADER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_PAYMENT_TRX_HEADERS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" MODIFY ("TRX_HEADER_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" ADD PRIMARY KEY ("TRX_HEADER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
