--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_ELEMENT_SET_DETAILS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_ELEMENT_SET_DETAILS" 
   (	"SET_LINE_ID" NUMBER, 
	"SET_HDR_ID" NUMBER, 
	"ELEMENT_ID" NUMBER, 
	"COMMENTS" VARCHAR2(250 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015927
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015927" ON "ETCHCM"."PTE_ELEMENT_SET_DETAILS" ("SET_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_ELEMENT_SET_DETAILS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_ELEMENT_SET_DETAILS" MODIFY ("SET_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_ELEMENT_SET_DETAILS" ADD PRIMARY KEY ("SET_LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PTE_ELEMENT_SET_DETAILS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_ELEMENT_SET_DETAILS" ADD CONSTRAINT "FK_PTE_ELMSET_DETAIL" FOREIGN KEY ("SET_HDR_ID")
	  REFERENCES "ETCHCM"."PTE_ELEMENT_SETS" ("SET_HDR_ID") ENABLE;
