--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_APPRAISAL_REQUEST_HEADERS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_APPRAISAL_REQUEST_HEADERS" 
   (	"APPRAISAL_HDR_ID" NUMBER, 
	"PROCESS_TYPE" VARCHAR2(100 BYTE), 
	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"APPROVED_FLAG" VARCHAR2(3 BYTE), 
	"APPROVED_DATE" DATE, 
	"TOTAL_COUNT" NUMBER, 
	"SUCCESS_COUNT" NUMBER, 
	"FAILURE_COUNT" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(100 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"UPLOADED_DATE" DATE, 
	"FILE_NAME" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0016105
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0016105" ON "ETCHCM"."PTE_APPRAISAL_REQUEST_HEADERS" ("APPRAISAL_HDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_APPRAISAL_REQUEST_HEADERS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_APPRAISAL_REQUEST_HEADERS" MODIFY ("APPRAISAL_HDR_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_APPRAISAL_REQUEST_HEADERS" ADD PRIMARY KEY ("APPRAISAL_HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
