--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_RATE_CARD_CONTRACTS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_RATE_CARD_CONTRACTS" 
   (	"RATE_CARD_CON_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"CONTRACT_NUMBER" VARCHAR2(80 BYTE), 
	"DECSRIPTION" VARCHAR2(250 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015650
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015650" ON "ETCHCM"."PTE_RATE_CARD_CONTRACTS" ("RATE_CARD_CON_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_RATE_CARD_CONTRACTS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_RATE_CARD_CONTRACTS" MODIFY ("RATE_CARD_CON_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_RATE_CARD_CONTRACTS" ADD PRIMARY KEY ("RATE_CARD_CON_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
