--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_PAYINV_AGENCY_CONFIRMS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_PAYINV_AGENCY_CONFIRMS" 
   (	"CONFIRM_HDR_ID" NUMBER, 
	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"PERIOD_NAME" VARCHAR2(30 BYTE), 
	"SEND_DATE" DATE, 
	"CONFIRM_TYPE" VARCHAR2(30 BYTE), 
	"REF_ID" NUMBER, 
	"REF_NUMBER" VARCHAR2(30 BYTE), 
	"REPORT_URL" VARCHAR2(300 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"HRSPOC_COMMENTS" VARCHAR2(1000 BYTE), 
	"AGENCY_NUMBER" NUMBER, 
	"AGENCY_USER_ID" NUMBER, 
	"AGENCY_COMMENTS" VARCHAR2(1000 BYTE), 
	"CONFIRMATION_STATUS" VARCHAR2(3 BYTE), 
	"SEND_EMAIL_STATUS" VARCHAR2(30 BYTE), 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"ACTION_DATE" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015921
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015921" ON "ETCHCM"."PTE_PAYINV_AGENCY_CONFIRMS" ("CONFIRM_HDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_PAYINV_AGENCY_CONFIRMS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYINV_AGENCY_CONFIRMS" MODIFY ("CONFIRM_HDR_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_PAYINV_AGENCY_CONFIRMS" ADD PRIMARY KEY ("CONFIRM_HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
