--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_REQUEST_HIST_HEADERS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_REQUEST_HIST_HEADERS" 
   (	"REQUEST_HDR_ID" NUMBER, 
	"PROCESS_TYPE" VARCHAR2(100 BYTE), 
	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"PERIOD_NAME" VARCHAR2(30 BYTE), 
	"CONTRACT_NUMBER" VARCHAR2(100 BYTE), 
	"AGENCY_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"CREATED_BY" VARCHAR2(100 BYTE), 
	"CREATION_DATE" DATE, 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"TOTAL_COUNT" NUMBER, 
	"SUCCESS_COUNT" NUMBER, 
	"FAILURE_COUNT" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015910
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015910" ON "ETCHCM"."PTE_REQUEST_HIST_HEADERS" ("REQUEST_HDR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_REQUEST_HIST_HEADERS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_REQUEST_HIST_HEADERS" MODIFY ("REQUEST_HDR_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_REQUEST_HIST_HEADERS" ADD PRIMARY KEY ("REQUEST_HDR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
