--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_STAFF_PAYMENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_STAFF_PAYMENT_DETAILS" 
   (	"PAYMENT_LINE_ID" NUMBER, 
	"PAYMENT_HDR_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"EMPLOYEE_NUMBER" VARCHAR2(80 BYTE), 
	"EMPLOYEE_FULL_NAME" VARCHAR2(1200 BYTE), 
	"PERIOD_NAME" VARCHAR2(30 BYTE), 
	"PERIOD_HOURS" NUMBER, 
	"AGENCY_PAYOUT" NUMBER, 
	"STAFF_PAYOUT" NUMBER, 
	"HOURLY_RATE" NUMBER, 
	"OT1_RATE" NUMBER, 
	"OT2_RATE" NUMBER, 
	"REGULAR_HOURS" NUMBER, 
	"FRIDAY_HOURS" NUMBER, 
	"PHD_HOURS" NUMBER, 
	"OT1_HOURS" NUMBER, 
	"OT2_HOURS" NUMBER, 
	"TOTAL_HOURS" NUMBER, 
	"REGULAR_AMOUNT" NUMBER, 
	"FRIDAY_AMOUNT" NUMBER, 
	"PHD_AMOUNT" NUMBER, 
	"OT1_AMOUNT" NUMBER, 
	"OT2_AMOUNT" NUMBER, 
	"TOTAL_AMOUNT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"TOTAL_DAYS" NUMBER, 
	"REMARKS" VARCHAR2(1000 BYTE), 
	"PERIOD_DAYS" NUMBER, 
	"ABSENCE_HOURS" NUMBER, 
	"ABSENCE_AMOUNT" NUMBER, 
	"WORKMAN_COMP_AMOUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015718
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015718" ON "ETCHCM"."PTE_STAFF_PAYMENT_DETAILS" ("PAYMENT_LINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_STAFF_PAYMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_STAFF_PAYMENT_DETAILS" MODIFY ("PAYMENT_LINE_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_STAFF_PAYMENT_DETAILS" ADD PRIMARY KEY ("PAYMENT_LINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PTE_STAFF_PAYMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_STAFF_PAYMENT_DETAILS" ADD CONSTRAINT "FK_PAYMENT_LINE_HRD_ID" FOREIGN KEY ("PAYMENT_HDR_ID")
	  REFERENCES "ETCHCM"."PTE_STAFF_PAYMENT_HEADERS" ("PAYMENT_HDR_ID") ENABLE;
