--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_SUPPLIERS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_SUPPLIERS" 
   (	"SUPPLIER_ID" NUMBER, 
	"SUPPLIER_NUMBER" NUMBER, 
	"SUPPLIER_NAME" VARCHAR2(360 BYTE), 
	"SUPPLIER_TYPE" VARCHAR2(50 BYTE), 
	"VAT_REGISTRATION_NUM" VARCHAR2(100 BYTE), 
	"START_DATE_ACTIVE" DATE, 
	"END_DATE_ACTIVE" DATE, 
	"ENABLED_FLAG" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015588
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015588" ON "ETCHCM"."PTE_SUPPLIERS" ("SUPPLIER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_SUPPLIERS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_SUPPLIERS" MODIFY ("SUPPLIER_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_SUPPLIERS" MODIFY ("SUPPLIER_NAME" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_SUPPLIERS" ADD PRIMARY KEY ("SUPPLIER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
