--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_ADDED_OVERTIME
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_ADDED_OVERTIME" 
   (	"PERSON_ID" NUMBER, 
	"PERSON_NUMBER" VARCHAR2(50 BYTE), 
	"PERIOD" VARCHAR2(30 BYTE), 
	"OVERTIME_TYPE" VARCHAR2(200 BYTE), 
	"OVERTIME_HOURS" NUMBER, 
	"APPROVED_OVERTIME_HOURS" NUMBER, 
	"APPROVAL_REQUSET_ID" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"UPDATED_BY" NUMBER, 
	"UPDATE_DATE" DATE, 
	"APPROVED_FLAG" VARCHAR2(1 BYTE), 
	"PROCCESSED_FLAG" VARCHAR2(1 BYTE), 
	"ADDED_OT_SEQ" NUMBER, 
	"HRSPOC_NOTES" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
