--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_DEPARTMENT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_DEPARTMENT_CATEGORY" 
   (	"DEPT_CATEGORY_CODE" VARCHAR2(100 BYTE), 
	"DEPT_CATEGORY_NAME" VARCHAR2(300 BYTE), 
	"ENABLED_FLAG" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"CREATION_DATE" DATE, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE), 
	"WEEKOFF1" VARCHAR2(20 BYTE), 
	"WEEKOFF2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
