--------------------------------------------------------
--  File created - Saturday-August-15-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PTE_PAYMENT_TRX_CCS
--------------------------------------------------------

  CREATE TABLE "ETCHCM"."PTE_PAYMENT_TRX_CCS" 
   (	"TRX_COST_CENTER_ID" NUMBER, 
	"TRX_HEADER_ID" NUMBER, 
	"TRX_BPA_ID" NUMBER, 
	"DEPARTMENT_ID" NUMBER, 
	"REGION" VARCHAR2(30 BYTE), 
	"LOCATION" VARCHAR2(30 BYTE), 
	"COST_CENTER" VARCHAR2(30 BYTE), 
	"EXPENSE_ACC" VARCHAR2(30 BYTE), 
	"CC_AMOUNT" NUMBER, 
	"CREATED_BY" NUMBER, 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_DATE" DATE, 
	"LAST_UPDATE_LOGIN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0015930
--------------------------------------------------------

  CREATE UNIQUE INDEX "ETCHCM"."SYS_C0015930" ON "ETCHCM"."PTE_PAYMENT_TRX_CCS" ("TRX_COST_CENTER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PTE_PAYMENT_TRX_CCS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_CCS" MODIFY ("TRX_COST_CENTER_ID" NOT NULL ENABLE);
  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_CCS" ADD PRIMARY KEY ("TRX_COST_CENTER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PTE_PAYMENT_TRX_CCS
--------------------------------------------------------

  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_CCS" ADD CONSTRAINT "FK_PTE_TRX_CC_BID" FOREIGN KEY ("TRX_BPA_ID")
	  REFERENCES "ETCHCM"."PTE_PAYMENT_TRX_BPAS" ("TRX_BPA_ID") ENABLE;
  ALTER TABLE "ETCHCM"."PTE_PAYMENT_TRX_CCS" ADD CONSTRAINT "FK_PTE_TRX_CC_HID" FOREIGN KEY ("TRX_HEADER_ID")
	  REFERENCES "ETCHCM"."PTE_PAYMENT_TRX_HEADERS" ("TRX_HEADER_ID") ENABLE;
